server.port=8083
spring.datasource.url=jdbc:mysql://localhost:3306/appointment_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
services.patient.url=http://localhost:8081
services.doctor.url=http://localhost:8082
services.email.url=http://localhost:8084
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger 